### PR TITLE
Add support of Python 3.10 and 3.11

### PR DESCRIPTION
**Pull request by FanwangM**
This PR is intended to add support for Python 3.11. 

The main hope is to fix the conda build problem of procrustes once this PR is merged, https://github.com/theochem/procrustes/actions/runs/3826363827. 

@tovrstra

### CODE REVIEW

**Comment by FanwangM** [comment]
The failing error in CI is pending for the new release of `invoke` to support Python 3.11 https://github.com/pyinvoke/invoke/issues/833. We can either wait for the new release or use the monkey patch.

**Comment by tovrstra** [comment]
@FanwangM I've taken out the `inspect` monkey patch since test pass without now. I'll merge. If the patch would still be needed, please let me know.

**Comment by FanwangM** [comment]
Sure. Thanks for taking care of this issue. @tovrstra

**Comment by tovrstra** [comment]
I understand now why you had the patched `inspect`. This was related to an old version of `wrapt`, used by PyLint. You can solve this issue by removing the pip environment that Roberto creates. Normally, this can be done with `rob nuke-testenv`, but that was also having a silly bug, preventing the actual removal. (Fixed in master branch, not released yet.) I'll release it soon.

**Pull request merged**
